### ISSUE TITLE
Could not download 'pyannote/segmentation-3.0' model.

### ISSUE THREAD

**Issue by Malkovitz** [JarodMica/audiosplitter_whisper#15]
Hello, I recently tried to spin up this program again, but it seems like there's some problem with speaker diarization.

It worked okay month ago, and I have not changed anything in the config file.

I tried to fix it generating new token and making sure I was gated in all three programs like in YouTube tutorial, but it's still failing.

`Could not download 'pyannote/segmentation-3.0' model.
It might be because the model is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:

   >>> Model.from_pretrained('pyannote/segmentation-3.0',
   ...                       use_auth_token=YOUR_AUTH_TOKEN)

If this still does not work, it might be because the model is gated:
visit https://hf.co/pyannote/segmentation-3.0 to accept the user conditions.
Traceback (most recent call last):
  File "c:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx==3.1.1', 'console_scripts', 'whisperx')())
  File "C:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\lib\site-packages\whisperx\transcribe.py", line 211, in cli
    diarize_model = DiarizationPipeline(use_auth_token=hf_token, device=device)
  File "C:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\lib\site-packages\whisperx\diarize.py", line 19, in __init__
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
  File "C:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\lib\site-packages\pyannote\audio\core\pipeline.py", line 136, in from_pretrained
    pipeline = Klass(**params)
  File "C:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\lib\site-packages\pyannote\audio\pipelines\speaker_diarization.py", line 128, in __init__
    model: Model = get_model(segmentation, use_auth_token=use_auth_token)
  File "C:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\lib\site-packages\pyannote\audio\pipelines\utils\getter.py", line 89, in get_model
    model.eval()
AttributeError: 'NoneType' object has no attribute 'eval'
Traceback (most recent call last):
  File "c:\Users\arkad\Desktop\ai\audiosplitter_whisper\split_audio.py", line 183, in <module>
    main()
  File "c:\Users\arkad\Desktop\ai\audiosplitter_whisper\split_audio.py", line 180, in main
    process_audio_files(input_folder, settings)
  File "c:\Users\arkad\Desktop\ai\audiosplitter_whisper\split_audio.py", line 148, in process_audio_files
    diarize_audio_with_srt(audio_file_path, srt_file, speaker_segments_dir)
  File "c:\Users\arkad\Desktop\ai\audiosplitter_whisper\split_audio.py", line 77, in diarize_audio_with_srt
    subs = pysrt.open(srt_file)
  File "C:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\lib\site-packages\pysrt\srtfile.py", line 151, in open
    source_file, encoding = cls._open_unicode_file(path, claimed_encoding=encoding)
  File "C:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\lib\site-packages\pysrt\srtfile.py", line 292, in _open_unicode_file
    encoding = claimed_encoding or cls._detect_encoding(path)
  File "C:\Users\arkad\Desktop\ai\audiosplitter_whisper\venv\lib\site-packages\pysrt\srtfile.py", line 279, in _detect_encoding
    file_descriptor = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\arkad\\Desktop\\ai\\Pudzian\\output\\plik.srt'`

**Comment by Malkovitz** [comment]
Nevermind, I just found the issue.

In YouTube video we are supposed to accept conditions for:
https://huggingface.co/pyannote/segmentation

but the script is requiring

https://huggingface.co/pyannote/segmentation-3.0

which looks like is never version of segmentation.

I agreed to 3.0 conditions, but it's getting stuck on >>Performing diarization...

**Comment by freeload101** [comment]
C:\whisperX\1\audiosplitter_whisper\venv\Lib\site-packages\whisperx\diarize.py
  https://hf.co/pyannote/speaker-diarization-3.1 for me ...
