### ISSUE TITLE
Exception has occurred: FileNotFoundError [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Arkanoidvfx** [JarodMica/audiosplitter_whisper#16]
i have accepted all user conditions on https://huggingface.co/pyannote but anyway getting this error below

(base) PS E:\Programs\AIVoiceProject\audiosplitter_whisper> venv\Scripts\activate              
(venv) (base) PS E:\Programs\AIVoiceProject\audiosplitter_whisper>  e:; cd 'e:\Programs\AIVoiceProject\audiosplitter_whisper'; & 'e:\Programs\AIVoiceProject\audiosplitter_whisper\venv\Scripts\python.exe' 'c:\Users\assas\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '64065' '--' 'E:\Programs\AIVoiceProject\audiosplitter_whisper\split_audio.py' 
CUDA is available. Running on GPU.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "E:\Programs\AIVoiceProject\audiosplitter_whisper\venv\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx==3.1.1', 'console_scripts', 'whisperx')())
  File "E:\Programs\AIVoiceProject\audiosplitter_whisper\venv\lib\site-packages\whisperx\transcribe.py", line 162, in cli
    model = load_model(model_name, device=device, device_index=device_index, compute_type=compute_type, language=args['language'], asr_options=asr_options, vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}, task=task, threads=faster_whisper_threads)
  File "E:\Programs\AIVoiceProject\audiosplitter_whisper\venv\lib\site-packages\whisperx\asr.py", line 52, in load_model
    model = WhisperModel(whisper_arch,
  File "E:\Programs\AIVoiceProject\audiosplitter_whisper\venv\lib\site-packages\faster_whisper\transcribe.py", line 128, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'E:\\Programs\\AIVoiceProject\\audiosplitter_whisper\\data\\output\\seriy4.srt'
  File "E:\Programs\AIVoiceProject\audiosplitter_whisper\split_audio.py", line 96, in extract_audio_with_srt
    subs = pysrt.open(srt_file)
  File "E:\Programs\AIVoiceProject\audiosplitter_whisper\split_audio.py", line 150, in process_audio_files
    extract_audio_with_srt(audio_file_path, srt_file, speaker_segments_dir)
  File "E:\Programs\AIVoiceProject\audiosplitter_whisper\split_audio.py", line 180, in main
    process_audio_files(input_folder, settings)
  File "E:\Programs\AIVoiceProject\audiosplitter_whisper\split_audio.py", line 183, in <module>
    main()
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Programs\\AIVoiceProject\\audiosplitter_whisper\\data\\output\\seriy4.srt'

**Comment by Arkanoidvfx** [comment]
i found the issue, my gtx 1080 ti do not support "**float16**"
so if you have same card you can set compute type to "**float32**" or "int8" 

```
def get_device_info():
    if torch.cuda.is_available():
        print('CUDA is available. Running on GPU.')
        return 'cuda', "float16" 
    else:
        print('CUDA is not available. Running on CPU.')
        return 'cpu', "int8"
```
        
in file **split_audio.py**

**Comment by freeload101** [comment]
I gave up and used CPU...not worth it got I hate python torch and CUDA ...
